# Generated by Django 5.1.6 on 2025-05-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(max_length=512)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failure', 'Failure'), ('Error', 'Error'), ('Warning', 'Warning')], default='Failure', max_length=30)),
                ('response_code', models.IntegerField()),
                ('actual_request_headers', models.JSONField(blank=True, null=True)),
                ('actual_request_body', models.TextField(blank=True, null=True)),
                ('response_time_ms', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='APITest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(db_index=True, max_length=255, unique=True)),
                ('endpoint', models.URLField()),
                ('http_method', models.CharField(choices=[('GET', 'Get'), ('POST', 'Post'), ('PATCH', 'Patch'), ('DELETE', 'Delete'), ('PUT', 'Put'), ('HEAD', 'Head'), ('OPTIONS', 'Options'), ('TRACE', 'Trace'), ('CONNECT', 'Connect')], default='GET', max_length=10)),
                ('headers', models.JSONField(blank=True, null=True)),
                ('body', models.JSONField(blank=True, null=True)),
                ('auth_type', models.CharField(choices=[('None', 'None'), ('Basic', 'Basic'), ('Bearer', 'Bearer'), ('API Key', 'API Key'), ('OAuth2', 'OAuth2'), ('JWT', 'JWT')], default='None', max_length=20)),
                ('auth_credentials', models.JSONField(blank=True, null=True)),
                ('expected_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttackSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=255, unique=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('impact_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LLMAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=255, unique=True)),
                ('analysis_result', models.TextField()),
                ('mitigation_suggestions', models.TextField()),
                ('risk_score', models.FloatField(default=0.0)),
                ('result_type', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical'), ('Unknown', 'Unknown'), ('Undetermined', 'Undetermined'), ('Not Specified', 'Not Specified'), ('Not Applicable', 'Not Applicable')], default='Low', max_length=30)),
                ('security_controls', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MITREAttackTactic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitre_attack_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('slug', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MITREAttackTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitre_attack_technique_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('slug', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('severity_weight', models.FloatField(default=1.0, help_text='Risk weighting factor (1.0-4.0)')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=255, unique=True)),
                ('summary', models.TextField()),
                ('recommendations', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical'), ('Unknown', 'Unknown'), ('Undetermined', 'Undetermined'), ('Not Specified', 'Not Specified'), ('Not Applicable', 'Not Applicable')], default='Low', max_length=30)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('expected_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=255, unique=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('response_body', models.JSONField(default=dict)),
                ('detected_vulnerabilities', models.JSONField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('custom_payload', models.JSONField(blank=True, null=True)),
                ('execution_parameters', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=255, unique=True)),
                ('schedule_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Running', 'Running'), ('Skipped', 'Skipped'), ('Interrupted', 'Interrupted'), ('Not Run', 'Not Run'), ('Not Applicable', 'Not Applicable'), ('Blocked', 'Blocked')], default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
