# Generated by Django 5.1.6 on 2025-04-30 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_scanner', '0002_securitytestcase_api_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitytestcase',
            name='api_test',
        ),
    ]
