# Generated by Django 5.1.6 on 2025-05-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_scanner', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='risk_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical'), ('Unknown', 'Unknown'), ('Undetermined', 'Undetermined'), ('Not Specified', 'Not Specified'), ('Not Applicable', 'Not Applicable')], default='Low', max_length=30),
        ),
    ]
