# Generated by Django 5.1.6 on 2025-04-30 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_scanner', '0003_remove_securitytestcase_api_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitytestcase',
            name='api_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_test_cases', to='api_scanner.apitest'),
        ),
    ]
