# Generated by Django 5.1.6 on 2025-04-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_scanner', '0004_securitytestcase_api_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='custom_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='execution_parameters',
            field=models.JSONField(default=dict),
        ),
    ]
