# Generated by Django 5.1.6 on 2025-04-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_scanner', '0005_testexecution_custom_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
