# Generated by Django 5.1.6 on 2025-04-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_scanner', '0006_testexecution_status_alter_testexecution_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testexecution',
            name='response_body',
            field=models.JSONField(default=dict),
        ),
    ]
