# Generated by Django 5.1.6 on 2025-05-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_scanner', '0007_alter_testexecution_response_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitest',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
