# Generated by Django 5.1.6 on 2025-05-02 00:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_scanner', '0008_alter_apitest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitreattacktactic',
            name='mitre_attack_id',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mitreattacktechnique',
            name='mitre_attack_technique_id',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
