# Generated by Django 5.1.6 on 2025-05-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_scanner', '0009_mitreattacktactic_mitre_attack_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitreattacktechnique',
            name='severity_weight',
            field=models.FloatField(default=1.0, help_text='Risk weighting factor (1.0-4.0)'),
        ),
    ]
