# Generated by Django 5.1.6 on 2025-05-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_scanner', '0010_mitreattacktechnique_severity_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitest',
            name='expected_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
