# Generated by Django 5.1.6 on 2025-05-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_scanner', '0011_apitest_expected_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='actual_request_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apilog',
            name='actual_request_headers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apilog',
            name='response_time_ms',
            field=models.FloatField(null=True),
        ),
    ]
