# Generated by Django 5.1.6 on 2025-05-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_scanner', '0012_apilog_actual_request_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitest',
            name='endpoint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
