# Generated by Django 5.1.6 on 2025-05-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_scanner', '0013_alter_apitest_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitytestcase',
            name='severity_breakdown',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securitytestcase',
            name='vulnerability_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
    ]
