# Generated by Django 5.1.6 on 2025-05-04 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_scanner', '0014_securitytestcase_severity_breakdown_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitytestcase',
            name='severity',
        ),
        migrations.AlterField(
            model_name='securitytestcase',
            name='api_test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_scanner.apitest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='securitytestcase',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='securitytestcase',
            name='expected_response',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='securitytestcase',
            name='mitre_attack_technique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_scanner.mitreattacktechnique'),
        ),
        migrations.AlterField(
            model_name='securitytestcase',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='securitytestcase',
            name='severity_breakdown',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='securitytestcase',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='securitytestcase',
            name='vulnerability_percentage',
            field=models.FloatField(),
        ),
    ]
