# Generated by Django 5.1.6 on 2025-05-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_scanner', '0015_remove_securitytestcase_severity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitytestcase',
            name='slug',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
