# Generated by Django 5.1.6 on 2025-05-04 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_scanner', '0016_alter_securitytestcase_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitytestcase',
            name='severity_breakdown',
        ),
        migrations.RemoveField(
            model_name='securitytestcase',
            name='vulnerability_percentage',
        ),
        migrations.AddField(
            model_name='securitytestcase',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical'), ('Unknown', 'Unknown'), ('Undetermined', 'Undetermined'), ('Not Specified', 'Not Specified'), ('Not Applicable', 'Not Applicable')], default='Low', max_length=30),
        ),
        migrations.AlterField(
            model_name='apitest',
            name='endpoint',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='securitytestcase',
            name='api_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_test_cases', to='api_scanner.apitest'),
        ),
        migrations.AlterField(
            model_name='securitytestcase',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='securitytestcase',
            name='expected_response',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='securitytestcase',
            name='mitre_attack_technique',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='security_test_cases', to='api_scanner.mitreattacktechnique'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='securitytestcase',
            name='payload',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
