# Generated by Django 5.1.6 on 2025-05-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_scanner', '0017_remove_securitytestcase_severity_breakdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitytestcase',
            name='severity_breakdown',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securitytestcase',
            name='vulnerability_percentage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
