# Generated by Django 5.1.6 on 2025-05-04 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_scanner', '0018_securitytestcase_severity_breakdown_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitytestcase',
            name='severity_breakdown',
        ),
        migrations.RemoveField(
            model_name='securitytestcase',
            name='vulnerability_percentage',
        ),
    ]
