# Generated by Django 5.1.6 on 2025-03-03 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('mitre_attack_id', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical'), ('Unknown', 'Unknown'), ('Undetermined', 'Undetermined'), ('Not Specified', 'Not Specified'), ('Not Applicable', 'Not Applicable')], default='Low', max_length=20)),
                ('payload', models.JSONField()),
                ('expected_response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='APITest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('endpoint', models.URLField()),
                ('http_method', models.CharField(choices=[('GET', 'Get'), ('POST', 'Post'), ('PATCH', 'Patch'), ('DELETE', 'Delete'), ('PUT', 'Put'), ('HEAD', 'Head'), ('OPTIONS', 'Options'), ('TRACE', 'Trace'), ('CONNECT', 'Connect')], default='GET', max_length=10)),
                ('headers', models.JSONField(blank=True, null=True)),
                ('body', models.JSONField(blank=True, null=True)),
                ('auth_type', models.CharField(choices=[('None', 'None'), ('Basic', 'Basic'), ('Bearer', 'Bearer'), ('API Key', 'API Key'), ('OAuth2', 'OAuth2'), ('JWT', 'JWT')], default='None', max_length=20)),
                ('auth_credentials', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_api_tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failure', 'Failure'), ('Error', 'Error'), ('Warning', 'Warning')], default='Failure', max_length=20)),
                ('response_code', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to=settings.AUTH_USER_MODEL)),
                ('api_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_logs', to='api_security.apitest')),
            ],
        ),
        migrations.CreateModel(
            name='AttackSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('impact_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_simulations', to='api_security.apitest')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attack_simulations', to=settings.AUTH_USER_MODEL)),
                ('security_test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_simulations', to='api_security.securitytestcase')),
            ],
        ),
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.IntegerField()),
                ('response_body', models.JSONField()),
                ('detected_vulnerabilities', models.JSONField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_executions', to='api_security.apitest')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_executions', to=settings.AUTH_USER_MODEL)),
                ('security_test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_executions', to='api_security.securitytestcase')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('recommendations', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('test_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api_security.testexecution')),
            ],
        ),
        migrations.CreateModel(
            name='LLMAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_result', models.TextField()),
                ('risk_score', models.IntegerField(default=0)),
                ('mitigation_suggestions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_analysis', to='api_security.testexecution')),
            ],
        ),
        migrations.CreateModel(
            name='TestSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Running', 'Running'), ('Skipped', 'Skipped'), ('Interrupted', 'Interrupted'), ('Not Run', 'Not Run'), ('Not Applicable', 'Not Applicable'), ('Blocked', 'Blocked'), ('Deferred', 'Deferred')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_schedules', to='api_security.apitest')),
                ('scheduled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_schedules', to=settings.AUTH_USER_MODEL)),
                ('security_test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_schedules', to='api_security.securitytestcase')),
            ],
        ),
    ]
